### ISSUE TITLE
Enable smooth scrollling

### ISSUE THREAD

**Issue by Keith-Web3** [KrishGaur1354/Beginners-Start#3]
The home, about and contact links in the header don't scroll to the respective sections they should when clicked. All they do is reload the page.

**Comment by Keith-Web3** [comment]
@KrishGaur1354 found another issue which is preventing me to implement the smooth scrolling feature.
There's a transparent image blocking some of the interactive elements on the header. I can't remove it since I don't know why it was put there in the first place. Here's an image below
![Screenshot (28)](https://user-images.githubusercontent.com/96974022/194512467-833c6ddb-fee7-4738-b294-1ea5fe0eaf3a.png)

**Comment by KrishGaur1354** [comment]
The project is Updated now Kindly check and Tell

**Comment by Keith-Web3** [comment]
It's still the same

**Comment by Keith-Web3** [comment]
I've fixed it. It was an issue with the width.
